version: '3.4'

services:
  backend:
      build:
        context: ./parking  # Path to the backend Dockerfile
      container_name: backend
      ports:
        - "8000:8000"  # Expose backend port (adjust as needed)
      environment:
        - DJANGO_SETTINGS_MODULE=parking.settings
        - NODE_ENV=production
        - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      depends_on:
        - db  # Example if there's a database service
      volumes:
        - ./parking:/app  # Mount the backend directory
        - /app/node_modules  # Avoid mounting node_modules from host
      networks:
        - app-network

  frontend:
    build:
      context: ./mapbox-gl-react-app  # Path to the frontend Dockerfile
    container_name: frontend
    ports:
      - "8080:8080"  # Expose frontend port (adjust as needed)
    environment:
      - NODE_ENV=production
    networks:
      - app-network
  db:
    image: postgres:latest  # Example database service
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
