# Generated by Django 4.2.2 on 2023-10-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NoParkingByLaw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bylaw_no", models.CharField(max_length=100)),
                ("source_id", models.CharField(max_length=10)),
                ("schedule", models.CharField(max_length=10)),
                ("schedule_name", models.CharField(max_length=100)),
                ("highway", models.CharField(max_length=100)),
                ("side", models.CharField(max_length=10, null=True)),
                ("between", models.CharField(max_length=200, null=True)),
                (
                    "prohibited_times_and_or_days",
                    models.CharField(max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RestrictedParkingByLaw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bylaw_no", models.CharField(max_length=100)),
                ("source_id", models.CharField(max_length=10)),
                ("schedule", models.CharField(max_length=10)),
                ("schedule_name", models.CharField(max_length=100)),
                ("highway", models.CharField(max_length=100)),
                ("side", models.CharField(max_length=10, null=True)),
                ("between", models.CharField(max_length=200, null=True)),
                ("times_and_or_days", models.CharField(max_length=200, null=True)),
                ("max_period_permitted", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
