# Generated by Django 4.2.2 on 2023-10-12 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Highway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Intersection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.FloatField(null=True)),
                ("lng", models.FloatField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NA", "Not Attempted"),
                            ("FS", "Fetched Success"),
                            ("FNF", "Fetched not found"),
                            ("TO", "Timed out"),
                        ],
                        default="NA",
                        max_length=3,
                    ),
                ),
                (
                    "cross_street",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cross_street",
                        to="whereToPark.highway",
                    ),
                ),
                (
                    "main_street",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_street",
                        to="whereToPark.highway",
                    ),
                ),
            ],
            options={
                "unique_together": {("main_street", "cross_street")},
            },
        ),
        migrations.CreateModel(
            name="ByLaw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_id", models.IntegerField(null=True)),
                ("schedule", models.CharField(max_length=10)),
                ("schedule_name", models.CharField(max_length=100)),
                ("side", models.CharField(max_length=10, null=True)),
                ("between", models.CharField(max_length=200, null=True)),
                ("times_and_or_days", models.CharField(max_length=200, null=True)),
                ("max_period_permitted", models.CharField(max_length=100, null=True)),
                (
                    "boundary_end",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boundary_end",
                        to="whereToPark.intersection",
                    ),
                ),
                (
                    "boundary_start",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boundary_start",
                        to="whereToPark.intersection",
                    ),
                ),
                (
                    "highway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="whereToPark.highway",
                    ),
                ),
            ],
            options={
                "unique_together": {("schedule", "source_id")},
            },
        ),
    ]
