# Generated by Django 4.2.2 on 2024-06-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whereToPark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bylaw',
            name='between',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='bylaw',
            name='schedule',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bylaw',
            name='side',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bylaw',
            name='times_and_or_days',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='highway',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
