# Generated by Django 4.2.2 on 2023-10-11 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("whereToPark", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="highway",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="intersection",
            unique_together={("main_street", "cross_street")},
        ),
    ]
