# Generated by Django 4.2.2 on 2023-10-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("whereToPark", "0002_alter_noparkingbylaw_source_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="noparkingbylaw",
            name="boundary_a_lat",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="noparkingbylaw",
            name="boundary_a_lng",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="noparkingbylaw",
            name="boundary_b_lat",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="noparkingbylaw",
            name="boundary_b_lng",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="restrictedparkingbylaw",
            name="boundary_a_lat",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="restrictedparkingbylaw",
            name="boundary_a_lng",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="restrictedparkingbylaw",
            name="boundary_b_lat",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="restrictedparkingbylaw",
            name="boundary_b_lng",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
