# Generated by Django 4.2.2 on 2023-10-11 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("whereToPark", "0002_alter_highway_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intersection",
            name="cross_street",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cross_street",
                to="whereToPark.highway",
            ),
        ),
        migrations.AlterField(
            model_name="intersection",
            name="main_street",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_street",
                to="whereToPark.highway",
            ),
        ),
    ]
