# Generated by Django 4.2.2 on 2023-10-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("whereToPark", "0003_noparkingbylaw_boundary_a_lat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="noparkingbylaw",
            name="between_street_a",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="noparkingbylaw",
            name="between_street_b",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="restrictedparkingbylaw",
            name="between_street_a",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="restrictedparkingbylaw",
            name="between_street_b",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
