# Generated by Django 4.2.2 on 2023-10-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("whereToPark", "0004_noparkingbylaw_between_street_a_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noparkingbylaw",
            name="boundary_a_lat",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="noparkingbylaw",
            name="boundary_a_lng",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="noparkingbylaw",
            name="boundary_b_lat",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="noparkingbylaw",
            name="boundary_b_lng",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="restrictedparkingbylaw",
            name="boundary_a_lat",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="restrictedparkingbylaw",
            name="boundary_a_lng",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="restrictedparkingbylaw",
            name="boundary_b_lat",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="restrictedparkingbylaw",
            name="boundary_b_lng",
            field=models.FloatField(null=True),
        ),
    ]
