# Generated by Django 4.2.2 on 2023-10-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("whereToPark", "0005_alter_noparkingbylaw_boundary_a_lat_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Highway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "street_end",
                    models.CharField(
                        choices=[
                            ("W", "West"),
                            ("E", "East"),
                            ("N", "North"),
                            ("S", "South"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="noparkingbylaw",
            old_name="between_street_a",
            new_name="cross_street_a",
        ),
        migrations.RenameField(
            model_name="noparkingbylaw",
            old_name="between_street_b",
            new_name="cross_street_b",
        ),
        migrations.RenameField(
            model_name="restrictedparkingbylaw",
            old_name="between_street_a",
            new_name="cross_street_a",
        ),
        migrations.RenameField(
            model_name="restrictedparkingbylaw",
            old_name="between_street_b",
            new_name="cross_street_b",
        ),
    ]
