# Generated by Django 4.2.2 on 2023-10-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("whereToPark", "0006_highway_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="highway",
            name="street_end",
            field=models.CharField(
                choices=[("W", "West"), ("E", "East"), ("N", "North"), ("S", "South")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="highway",
            unique_together={("name", "street_end")},
        ),
    ]
