# Generated by Django 4.2.2 on 2023-10-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("whereToPark", "0007_alter_highway_street_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="noparkingbylaw",
            name="boundary_status_a",
            field=models.CharField(
                choices=[
                    ("NA", "Not Attempted"),
                    ("FS", "Fetched Success"),
                    ("FNF", "Fetched not found"),
                    ("TO", "Timed out"),
                ],
                default="NA",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="noparkingbylaw",
            name="boundary_status_b",
            field=models.CharField(
                choices=[
                    ("NA", "Not Attempted"),
                    ("FS", "Fetched Success"),
                    ("FNF", "Fetched not found"),
                    ("TO", "Timed out"),
                ],
                default="NA",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="restrictedparkingbylaw",
            name="boundary_status_a",
            field=models.CharField(
                choices=[
                    ("NA", "Not Attempted"),
                    ("FS", "Fetched Success"),
                    ("FNF", "Fetched not found"),
                    ("TO", "Timed out"),
                ],
                default="NA",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="restrictedparkingbylaw",
            name="boundary_status_b",
            field=models.CharField(
                choices=[
                    ("NA", "Not Attempted"),
                    ("FS", "Fetched Success"),
                    ("FNF", "Fetched not found"),
                    ("TO", "Timed out"),
                ],
                default="NA",
                max_length=30,
            ),
        ),
    ]
